name: build-enclave-image-dev
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: enclave-signer-registry

jobs:
  build-app:
    name: build-app
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          push: true
          platforms: linux/amd64
          tags: dimozone/${{ env.APP_NAME }}:${{ steps.slug.outputs.sha7 }}, dimozone/${{ env.APP_NAME }}:latest

      - name: Extract PCR measurements
        id: extract-pcrs
        run: |
          # Set the output with proper formatting
          echo "measurements<<EOF" >> $GITHUB_OUTPUT
          echo "PCR Measurements:" >> $GITHUB_OUTPUT
          docker run --rm -e LOG_LEVEL=NONE dimozone/${{ env.APP_NAME }}:${{ steps.slug.outputs.sha7 }} /run.sh measurements >> $GITHUB_OUTPUT
          printf "\nEOF\n" >> $GITHUB_OUTPUT

      - name: Update image version
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: "charts/enclave-signer-registry/values.yaml"
          value: ${{ steps.slug.outputs.sha7 }}
          branch: main
          message: "Update Image Version to ${{ steps.slug.outputs.sha7 }}\n\n${{ steps.extract-pcrs.outputs.measurements }}"
          changes: |
            {
              "app.image.tag": "${{ steps.slug.outputs.sha7 }}"
            }
