name: build-enclave-image-prod
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  APP_NAME: enclave-signer-registry

jobs:
  build-app:
    name: build-app
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Build and push enclave app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          load: false
          platforms: linux/amd64
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          tags: dimozone/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }}, dimozone/${{ env.APP_NAME }}:latest

      - name: Extract PCR measurements
        id: extract-pcrs
        run: |
          # Set the output with proper formatting
          echo "measurements<<EOF" >> $GITHUB_OUTPUT
          echo "PCR Measurements:" >> $GITHUB_OUTPUT
          docker run --rm -e LOG_LEVEL=NONE dimozone/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }} /run.sh measurements >> $GITHUB_OUTPUT
          printf "\nEOF\n" >> $GITHUB_OUTPUT

      - name: Update image version
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: "charts/${{ env.APP_NAME }}/values-prod.yaml"
          value: ${{ steps.tag.outputs.tag }}
          branch: main
          message: "Update Image Version to ${{ steps.tag.outputs.tag }}\n\n${{ steps.extract-pcrs.outputs.measurements }}"
          changes: |
            {
              "app.image.tag": "${{ steps.tag.outputs.tag }}"
            }
